### ISSUE TITLE
Can you create button to enable or disable InaSAFE: Analysis environment ready

### ISSUE THREAD

**Issue by adissadis** [inasafe/inasafe#2804]
### Problem
Currently, while we doing test to InaSAFE 3.4, there some issue about how InaSAFE work. I'm not good to explain this, but when you enable InaSAFE plugin, the InaSAFE will create/do some task to see if the InaSAFE analysis environment is ready or not to be execute. There will be some of message above map canvas like this:
![image](https://cloud.githubusercontent.com/assets/2520159/15356134/1f380186-1d21-11e6-9c75-24837708b74b.png)
From above message, i'm thinking that after you put some data in and those data already have InaSAFE keyword on this, InaSAFE will try to run some process to check whether those data is ready to run (based on analysis area or maybe the keyword or else)

This process will eat some RAM and while this not really affect when we doing some analysis with vector-vector data, this process really eat RAM for raster data. Here's my screenshot for the amount of RAM used for InaSAFE to checking the analysis environment for Raster data
![image](https://cloud.githubusercontent.com/assets/2520159/15356257/eca683ae-1d21-11e6-9d7d-c44b9dd069cb.png)

And this is for another screenshot for another raster data:
![image](https://cloud.githubusercontent.com/assets/2520159/15356274/07448a12-1d22-11e6-829a-fd66911ef553.png)

Based on those screenshot, for big raster data like Java population or Sumatera Population from AsiaPop, InaSAFE will need those amount of ram to check the environment.

This become a problem to people who only have small amount of RAM in their laptop (for example only 2GB or 4GB). They will encounter lag or freeze or a long time and sometimes their laptop will crashed or QGIS mini dump.

Actually this problem can be solved by crop the raster layer into small area based on their area of interest but i proposed some of solution to create some option in InaSAFE's Options to enable or disable this feature.

### Expected Behaviour
If they disable the option to "Disable InaSAFE automatically check analysis environment" in InaSAFE's Options the InaSAFE won't perform automatic analysis environment check.

### Environment
Windows 10 64bit 16GB ram
QGIS 2.8.9
InaSAFE 3.4

### Proposed Solution
Create some flag to enable or disable InaSAFE automatic analysis environment check

**Comment by ismailsunni** [comment]
If we implemented this, I think we should set the default value to yes.

**Comment by timlinux** [comment]
There is already support for this:

![Uploading Screen Shot 2016-05-23 at 10.52.39.png…]()

**Comment by Gustry** [comment]
@timlinux, correct me if I'm wrong, but these options are only on the UI. The computation will occur whatever these options are checked or not in the background.
https://github.com/inasafe/inasafe/blob/develop/safe/gui/widgets/dock.py#L2107

So I think we should re-open this issue.

**Comment by adissadis** [comment]
Yes what @Gustry said was right. The process still occurred even i already disable those two options in InaSAFE analysis area.

**Comment by timlinux** [comment]
To be honest I don;t think it is the 'Analysis ready' message that takes a long time to display.  Every time you pan / zoom / hide layers / show layers InaSAFE does a bunch of calculations to determine the analysis environment.

I did some testing here witching the ram consumption as you did and I don't really see any significant change in ram consumption when panning etc. I think you system is probably using swap memory. I'll do some more poking around to see what I can find....

**Comment by timlinux** [comment]
Ok I took a deep dive into this on the plane on the way back from Jakarta :-P

Here is the basic issue:

When ever we pan / zoom / change layers etc in QGIS a signal is fired to check the validity of the analysis environment. The traceback down the call stack looks like this:

![screen shot 2016-07-25 at 9 35 01 am](https://cloud.githubusercontent.com/assets/178003/17094053/1d4b871a-524d-11e6-8cbb-a4b830ce50f7.png)


(Sorry the screenshot is a bit blurry)

Basically read_layer is used to get the extents of the layers, but read_layer does not do a lazy read of the data like QGIS MapLayer's do. So it reads all the data into ``safe_layer.data`` each time this event happens.

To fix this we can do:

a) implement #2987 and discontinue the use of safe_layer

and / or

b) refactor safe_layer (for both raster and vector data) so that it only does a full data scan at the point when ``self.data`` is used.

Option b is going to take a bit of work since it does not use accessors  in safe_layer so we don't know what side effects changing this behaviour will have. I will put aside say 4 hours to come up with a fix and if I can't come up with something reasonable I propose to hold on fixing this until 3.6 comes our which will implement #2987.

**Comment by timlinux** [comment]
Ok I have made a fix (for rasters anyway):

Before optimisation: 15s to do a simple pan

![qgis](https://cloud.githubusercontent.com/assets/178003/17331649/26a10986-58cc-11e6-91fd-cfa4a56c13f6.gif)


After optimisation: 4s to do a simple pan

![qgis](https://cloud.githubusercontent.com/assets/178003/17331523/96acdab2-58cb-11e6-88ff-a452d7b5bd42.gif)
